name: telegram-bot
services:
  - name: telegram-bot-service
    runtime: docker
    build:
      type: dockerfile
      dockerfile_path: ./Dockerfile
    env:
      - name: BOT_TOKEN
        value: "${BOT_TOKEN}" # Set this in Koyeb environment variables
      - name: MONGO_URI
        value: "${MONGO_URI}" # Set this in Koyeb environment variables
